.DEFAULT_GOAL := help
EXEC_PHP?=

##
## Project setup
##---------------------------------------------------------------------------
.PHONY: install up start stop reset clear

install: start ## Install and start the project with vendors update

start: vendor ## Start the project with vendors update

stop: ## Remove docker containers

reset: clear start ## Stop clear and install

clear: stop ## clear project

##
## Dependencies
##---------------------------------------------------------------------------
vendor: composer.lock
	$(EXEC_PHP) composer install

composer.lock: composer.json
	@echo PHP vendors are not up to date.

##
## Utilities
##---------------------------------------------------------------------------
.PHONY: help

help:
@grep -E '(^[a-zA-Z_-]+:.*?##.*$$)|(^##)' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[32m%-30s\033[0m %s\n", $$1, $$2}' | sed -e 's/\[32m##/[33m/'

-include Makefile.local
